# Form implementation generated from reading ui file '.\res.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Result(object):
    def setupUi(self, Result):
        Result.setObjectName("Result")
        Result.resize(981, 744)
        font = QtGui.QFont()
        font.setPointSize(14)
        Result.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Result)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Result)
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Func = QtWidgets.QLabel(parent=Result)
        self.Func.setText("")
        self.Func.setObjectName("Func")
        self.horizontalLayout.addWidget(self.Func)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.res_func_table = QtWidgets.QTableWidget(parent=Result)
        self.res_func_table.setObjectName("res_func_table")
        self.res_func_table.setColumnCount(3)
        self.res_func_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.res_func_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.res_func_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.res_func_table.setHorizontalHeaderItem(2, item)
        self.res_func_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.res_func_table)

        self.retranslateUi(Result)
        QtCore.QMetaObject.connectSlotsByName(Result)

    def retranslateUi(self, Result):
        _translate = QtCore.QCoreApplication.translate
        Result.setWindowTitle(_translate("Result", "Результат"))
        self.label.setText(_translate("Result", "Уравнение :"))
        item = self.res_func_table.horizontalHeaderItem(0)
        item.setText(_translate("Result", "№"))
        item = self.res_func_table.horizontalHeaderItem(1)
        item.setText(_translate("Result", "f(x)"))
        item = self.res_func_table.horizontalHeaderItem(2)
        item.setText(_translate("Result", "Координата"))
